### ISSUE TITLE
Does the yaml config adhere to yaml standards?

### ISSUE THREAD

**Issue by wjdragon** [cminyard/ser2net#107]
I am using the ser2net.yaml file to store and reload serial configuration on a server.  The server will have four serial ports, each of which is accessed using a different port (is this the right way to do it?).  At the moment, I am testing with a server with a single serial port (the working one is ttyS1).  My YAML looks like this:

```
%YAML 1.1
---

define: &banner Connected to port \N(\d)\r\n

default: &local
    name: local
    value: true
    class: serialdev

default: &mdns
    name: mdns
    value: true

default: &mdns_sysattrs
    name: mdns-sysattrs
    value: true

admin: &admin1
    accepter: mux,certauth,ssl,tcp,2000

connection: &ttyS0
    accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3001
    connector: serialdev,/dev/ttyS0,9600N81
    options:
        banner: *banner

connection: &ttyS1
    accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3002
    connector: serialdev,/dev/ttyS1,9600N81
    options:
        banner: *banner

connection: &ttyS2
    accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3003
    connector: serialdev,/dev/ttyS2,9600N81
    options:
        banner: *banner

connection: &ttyS3
    accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3004
    connector: serialdev,/dev/ttyS3,9600N81
    options:
        banner: *banner
```

At least I think it works, as on the client side I just run ```gtlssh -p 3002 <server ip>```, it connects and I am able to see serial information.

I am creating a python-based menu system where a remote user can login to the server and make changes to the ser2net configuration.  It scans the YAML file, presents the serial information, and when the user saves changes it'll generate a new YAML and restart the ser2net instance.  However, my yaml configuration does not conform to yaml specs and yaml libraries won't read the last three connections.

When I run a remote admin to the server and run "showport", all of the connections show up correctly.  This makes me to think that ser2net is able to read this correct and is working.

Is there a more appropriate yaml file that conforms to the spec that I should be using?

**Comment by cminyard** [comment]
On Thu, Nov 09, 2023 at 04:08:15PM -0800, wjdragon wrote:
> I am using the ser2net.yaml file to store and reload serial
> configuration on a server.  The server will have four serial ports,
> each of which is accessed using a different port (is this the right
> way to do it?).

Yes, that's correct.  There are other ways to do it, but generally, you
want an IP port to map to a serial port.

> At the moment, I am testing with a server with a
> single serial port (the working one is ttyS1).  My YAML looks like
> this:
> 
> ```
> %YAML 1.1
> ---
> 
> define: &banner Connected to port \N(\d)\r\n
> 
> default: &local
>     name: local
>     value: true
>     class: serialdev
> 
> default: &mdns
>     name: mdns
>     value: true
> 
> default: &mdns_sysattrs
>     name: mdns-sysattrs
>     value: true
> 
> admin: &admin1
>     accepter: mux,certauth,ssl,tcp,2000
> 
> connection: &ttyS0
>     accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3001
>     connector: serialdev,/dev/ttyS0,9600N81
>     options:
>         banner: *banner
> 
> connection: &ttyS1
>     accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3002
>     connector: serialdev,/dev/ttyS1,9600N81
>     options:
>         banner: *banner
> 
> connection: &ttyS2
>     accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3003
>     connector: serialdev,/dev/ttyS2,9600N81
>     options:
>         banner: *banner
> 
> connection: &ttyS3
>     accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3004
>     connector: serialdev,/dev/ttyS3,9600N81
>     options:
>         banner: *banner
> ```
> 
> At least I think it works, as on the client side I just run ```gtlssh -p 3002 <server ip>```, it connects and I am able to see serial information.
> 
> I am creating a python-based menu system where a remote user can login
> to the server and make changes to the ser2net configuration.  It scans
> the YAML file, presents the serial information, and when the user
> saves changes it'll generate a new YAML and restart the ser2net
> instance.  However, my yaml configuration does not conform to yaml
> specs and yaml libraries won't read the last three connections.

Well, this is a mistake on my part.  Apparently YAML doesn't allow
duplicate node names in a mapping.  If you search for "duplicate node
names in a mapping python yaml" you will get some useful information.

You will also run into issues parsing the & and * values.

I'm going to need to fix this :(.

-corey

> 
> When I run a remote admin to the server and run "showport", all of the
> connections show up correctly.  This makes me to think that ser2net is
> able to read this correct and is working.
> 
> Is there a more appropriate yaml file that conforms to the spec that I
> should be using?

**Comment by cminyard** [comment]
On Fri, Nov 10, 2023 at 10:03:38AM -0600, Corey Minyard wrote:
> The other option to "fix" this that I cam up with would be to add a
> "type" field to each node, like:
> 
> ```
> ttyS3:
>   type: connection
>   accepter: ....
> ```

I had some more ideas.

You could have the file be separate section, something like:

```
<sectionname>:
  define:...
  connection:
    ...

<sectionname2>:
  define:...
```

and so forth.  The section names would need to be unique, but could be
ignored.  Seems kind of unnatural, still.

Another thought was to separate the file into different documents with
"---"  So:
```
%YAML 1.1
---
connection:
  name: ...
  accepter: ...
---
connection:
  name: ...
  accepter: ...
```
and so forth.  In any case, the anchors (&name) are not going to work.

Still thinking...

-corey

**Comment by wjdragon** [comment]
> On Thu, Nov 09, 2023 at 04:08:15PM -0800, wjdragon wrote: I am using the ser2net.yaml file to store and reload serial configuration on a server. The server will have four serial ports, each of which is accessed using a different port (is this the right way to do it?). At the moment, I am testing with a server with a single serial port (the working one is ttyS1). My YAML looks like this:
> Well this was a most unfortunate mistake. I have pushed up experimental changes to the git repository that enables a fully yaml compliant config file as a different type of file. To use that, your new file will be: ``` %YAML 1.1 --- defines: banner1: Connected to port \N(\d)\r\n defaults: local: value: true class: serialdev mdns: value: true mdns-sysattrs: value: true admins: admin1: accepter: mux,certauth,ssl,tcp,2000 connections: ttyS0: accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3001 connector: serialdev,/dev/ttyUSB0,9600n81 options: banner: =(banner1) ttyS1: accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3002 connector: serialdev,/dev/ttyS1,9600N81 options: banner: =(banner1) ttyS2: accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3003 connector: serialdev,/dev/ttyS2,9600N81 options: banner: =(banner1) ttyS3: accepter: telnet(rfc2217),mux,certauth(),ssl,tcp,3004 connector: serialdev,/dev/ttyS3,9600N81 options: banner: =(banner1) ``` This should be fully compliant YAML. ser2net will see this file format and auto-detect that it's the different version. You can't mix versions. The other option to "fix" this that I cam up with would be to add a "type" field to each node, like: ``` ttyS3: type: connection accepter: .... ``` but that seems fairly unnatural in YAML. Any other ideas would be welcome, it's really not that hard to change. Documention takes longer than coding here. Is it possible for you to compile the sources from github and try this? I'd like comments from you (and anyone else) about this. Thanks,
> […](#)
> -corey

Your first fix works, with lumping all of the connection names as their own sections in the "connections".  The ser2net binary loads them ok, and I can gtlssh from a client and connect to the serial port just fine.  ruamel and pyYAML libraries are both able to parse the new yaml configuration layout.  Excellent work!

**Comment by wjdragon** [comment]
To be honest, I think the various ways to organize the yaml file has pros and cons, depending on how convenient it is for the end user.

```
connection:
   <name>:
        accepter: 
        connector:
   <name>:
        accepter:
        connector:
```
To me, this makes the most sense.  These are all connections, and having them grouped into one area logically fits.  I can see it becoming a nuisance if a server has a lot of connections, however.

Having connectors in multiple files might be a good way to split up the connectors, but I think it makes it more difficult to organize it on the server end.  Now you're dealing with various yaml configurations instead of a single file.

The <section name> approach fits nicely with the single file approach, but I don't think it's a YAML compliant feature (at least the way it is suggested here)

If we're simply looking at YAML compliance, your first approach fits the bill.  It is easy to read, and groups everything in YAML compliance form.  That one gets my vote!
