### ISSUE TITLE
Unknown (debug?) message spam when running ser2net

### ISSUE THREAD

**Issue by ffolkes1911** [cminyard/ser2net#125]
I have noticed that `ser2net` spams some unknown messages to terminal:  
```
...
A: 1
B: 4 none
C: 0
...
```
Nothing else is ever being printed, only these 3 and always identical lines every 0.5-1.5s.  
Messages don't seem to appear on connect/usage of telnet. Nothing was done on admin console and spam persists after restarting `ser2net` (which I assume resets any monitoring and other changes done over admin console)

Noticed problem with `ser2net` `4.6.0` so I built latest `ser2net` (and `gensio`) master (`4.6.1+`), but messages still appear.  
There could very well be problems with our FTDI devices, but I don't see any problematic messages in `dmesg`, so I would like to figure out what those messages mean.   

Running `ser2net` with `ser2net -c /etc/ser2net/ser2net.yaml -n -d`, had also added `-l` but that did not change output.  

OS: Ubuntu 22.04.4 LTS

<details><summary>Config YAML</summary>

```
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
# 
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

admin: &admin1
  accepter: tcp,2000


#########################

connection: &con101
  accepter: telnet(rfc2217),tcp,38101
  connector: serialdev,/dev/serial/by-path/pci-0000:00:14.0-usb-0:10.5:1.0-port0,115200n81,local
  enable: on
  timeout: 18000
  options:
    max-connections: 7

...

```

</details>
