### ISSUE TITLE
ser2net[323291]: The dev write(2) for port con5001 had error: Object was not ready for operation

### ISSUE THREAD

**Issue by pieterverberne** [cminyard/ser2net#133]
I have another issue. What happens:

Occassianally when connecting to ser2net with telnet I don't get the expected output. Instead of the 'current' output of a serial console, I get something that is already present in the buffer:

```
telnet 10.7.0.51 5001
ser2net port telnet(rfc2217),tcp,5001 device serialdev,/dev/ttyDUT1,115200n81,local,hangup-when-done=no [115200N81,CLOCAL] end ser2net banner

19708] Read 18 DATA:ff:ff:ff:ff:ff:ff:ff:ff:ff:f
```

When telnetting again, I immediately get the exact same output. The session is not responsive. When I stop ser2net (or do `disconnect con5001`) and use cu to connect to /dev/ttyDUT1 it works immediately.

It is pretty hard to reproduce. Usually it happens after 25 minutes of running some auto tests that connect to ser2net several times. One time i did see this error message: `ser2net[323291]: The dev write(2) for port con5001 had error: Object was not ready for operation`.

Do you have any advice on troubleshooting this issue?

I'm trying this on master, with Ubuntu 22.04

```

define: &banner ser2net port \p device \d [\B] end ser2net banner\r\n\r\n

admin:
    accepter: tcp,4999


connection: &con5001
    accepter: telnet(rfc2217),tcp,5001
    timeout: 1800
    enable: on
    options:
      banner: *banner
      kickolduser: false
      max-connections: 100
      telnet-brk-on-sync: true
    connector: serialdev,/dev/ttyDUT1,115200n81,local,hangup-when-done=no

```
