### ISSUE TITLE
Cannot send BRK character

### ISSUE THREAD

**Issue by dima1308** [cminyard/ser2net#136]
I'm using ser2net ver `4.6.0-1build2` from Ubuntu 24.04 LTS distribution for Raspberry PI.
When I'm trying to send the BRK character from the telnet client, the BRK character is not sent.

To send the BRK character, I do the following steps:
1. Connect to Raspberry PI that is running ser2net: 
```
telnet 10.40.1.127 3001
```
2. Press CTRL + ] to enter the Escape Sequence Command Mode on the telnet client
3. Type `send brk` to send the BRK character

At this point, I anticipate the BRK character to be set, but it is not.
When I do the same steps with ser2net version 4.3.3 (from the Raspbian distribution), the BRK character is sent as expected.

The ser2net configuration file is:
```
pi@spiderpisw17:~$ cat /etc/ser2net.yaml
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

default:
  name: speed
  value: 115200
  class: serialdev

connection: &3001
    accepter: telnet(rfc2217),3001
    timeout: 43200
    enable: on
    connector: serialdev,/dev/ttyUSB-spider17b,115200n81,local
    options:
      banner: *banner
      kickolduser: false
      max-connections: 3

admin:
    accepter: telnet(rfc2217),3000
```

Can someone please help me with this issue?
