### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ffolkes1911** [cminyard/ser2net#143]
ser2net segfaults roughly within a day on a certain PC. Here's some info from latest core dump:

<details><summary>Click to expand</summary>

```
TESTPC@TESTPC:~$ coredumpctl info
           PID: 3328456 (ser2net)
           UID: 1000 (TESTPC)
           GID: 1000 (TESTPC)
        Signal: 11 (SEGV)
     Timestamp: Tue 2025-06-03 15:34:05 EEST (6min ago)
  Command Line: ser2net -c /etc/ser2net/ser2net.yaml -n -d -l
    Executable: /usr/local/sbin/ser2net
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-f946c5d8-87f6-4db4-a1fe-815905422146.scope
          Unit: user@1000.service
     User Unit: vte-spawn-f946c5d8-87f6-4db4-a1fe-815905422146.scope
         Slice: user-1000.slice
     Owner UID: 1000 (TESTPC)
       Boot ID: 0cb88d3810584cf2bc32784d8aaa5a37
    Machine ID: ede2018e83ec4e2191c36c8c3208d2c2
      Hostname: TESTPC
       Storage: /var/lib/systemd/coredump/core.ser2net.1000.0cb88d3810584cf2bc32784d8aaa5a37.3328456.1748954045000000.zst (present)
  Size on Disk: 90.4K
       Message: Process 3328456 (ser2net) of user 1000 dumped core.
                
                Stack trace of thread 3328456:
                #0  0x00007edb9178b75d __strlen_avx2 (libc.so.6 + 0x18b75d)
                #1  0x0000630f94c59567 ser_control_set (ser2net + 0x8567)
                #2  0x00007edb91929883 serconf_call_cdone (libgensio_serialdev.so + 0x3883)
                #3  0x00007edb9196a4db process_runners (libgensioosh.so.10 + 0x164db)
                #4  0x00007edb9196c96f sel_select_intr_sigmask (libgensioosh.so.10 + 0x1896f)
                #5  0x00007edb91969636 i_wait_for_waiter_timeout (libgensioosh.so.10 + 0x15636)
                #6  0x00007edb919698b2 gensio_unix_wait (libgensioosh.so.10 + 0x158b2)
                #7  0x0000630f94c567a7 main (ser2net + 0x57a7)
                #8  0x00007edb9162a1ca __libc_start_call_main (libc.so.6 + 0x2a1ca)
                #9  0x00007edb9162a28b __libc_start_main_impl (libc.so.6 + 0x2a28b)
                #10 0x0000630f94c57005 _start (ser2net + 0x6005)
                ELF object binary architecture: AMD x86-64
```

</details>

I can send over the dump itself if you need.  

Error frequency:  

<details><summary>Click to expand</summary>

```
start at Thu May 29 09:35:50 AM EEST 2025
Segmentation fault (core dumped)
start at Thu May 29 06:18:53 PM EEST 2025
Segmentation fault (core dumped)
start at Thu May 29 08:01:57 PM EEST 2025
Segmentation fault (core dumped)
start at Fri May 30 12:48:23 AM EEST 2025
Segmentation fault (core dumped)
start at Sat May 31 05:54:39 AM EEST 2025
Segmentation fault (core dumped)
start at Sat May 31 07:05:03 AM EEST 2025
Segmentation fault (core dumped)
start at Sat May 31 08:45:39 AM EEST 2025
Segmentation fault (core dumped)
start at Sat May 31 11:55:03 PM EEST 2025
Segmentation fault (core dumped)
start at Mon Jun  2 12:30:02 AM EEST 2025
Segmentation fault (core dumped)
start at Tue Jun  3 08:04:19 AM EEST 2025
Segmentation fault (core dumped)
start at Tue Jun  3 03:34:05 PM EEST 2025
```

</details>

ser2net.yaml (nothing really different from other computers):  

<details><summary>Click to expand</summary>

```
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
# 
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport


admin: &admin1
  accepter: tcp,2000


#########################




# initial serial: A50285BI, full path: /dev/serial/by-path/pci-0000:00:14.0-usbv2-0:2.3:1.0-port0
connection: &con001
  accepter: telnet(rfc2217),tcp,38001
  connector: serialdev,/dev/serial/by-path/pci-0000:00:14.0-usbv2-0:2.3:1.0-port0,115200n81,local
  enable: on
  timeout: 18000
  options:
    max-connections: 7
...
```

</details>

Affected computer uses Ubuntu 24.04.2, CPU CORE i3-7100, `ser2net` version 4.6.5 (compiled from source), but issue was present before that, maybe 4.6.3 or 4.6.4. `gensio` was slightly out of date, but updating it did not help, coredump is nearly identical, only change is `serconf_call_cdone (libgensio_serialdev.so + 0x38ab)` 

Another computer with same OS, but different CPU (CORE i5-9600), has no problems running it for 4 days now, `ser2net` v4.6.5 commit `7189a5d`, gensio v2.8.14 commit `0b478936` .  

As a side note, it would be nice if version args would be the same for `ser2net` and `gensio` :D `gensio` uses `--version` but `ser2net` uses `-v`
