### ISSUE TITLE
ser2net to a linux system: no arrow keys, local echo no disabled

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/ser2net#144]
Hi,

here is the ser2net configuration that I think used to work before:

```
connection: &con10115
  accepter: tcp,localhost,10115
  enable: on
  options:
    banner: *banner
    kickolduser: true
    telnet-brk-on-sync: true
  connector: serialdev,/dev/ttyUSB0,115200n81,local
```

When i use this ser2net connection to connect to a raspberry pi, my arrow keys in the shell don't work (displayin the raw ^[[A, a few of weird characters like [[48;1R^[[48;101R appear when I try to log in, and the password is echoed back verbatim when logging in.

screen /dev/ttyUSB0 115200 in the same terminal with the same hardware setup works just fine.

Did something in ser2net's configuration change in the last years that causes a known good configuration to no longer work? I have Debian unstable with gensio 2.8.13 and ser2net 4.6.4

If there is a better way to ask support questions, please let me know.

Greeitngs
Marc
