### ISSUE TITLE
disconnected USB won't release socket

### ISSUE THREAD

**Issue by mpflaga** [cminyard/ser2net#22]
I have found an issue using Ser2net 4.1.1 with gensio 1.3.1 using the following configuration, where if the USB device is disconnected while a Socket is established then something goes wrong, even if only disconnected briefly. The socket remains established and un-usable. Unfortunately, the socket remains even after the remote side has disconnected, resulting in the channel becoming unavailable. I would expect when the USB device is destructed that the associated socket would drop, releasing local resources. I also note that it cannot be disconnected using the control console. The only method I have found to recover is to stop and restart ser2net other than rebooting. I am using a Raspberry Pi 3B "8 (jessie)" with USB to Serial adaptors on a USB HUB.

I am not sure what logs I can supply that would help. As I don't know if the problem is with gensio or with ser2net. Whereas the problem is very reproducible and I suspect would demonstrate on any other Linux system.

Your assistance is appreciated.

```
%YAML 1.1
---

admin:
  accepter: telnet,1999

define: &banner1 Ser2net \N,\p,\d,\I \r\n

connection: &2001
  accepter: telnet,tcp,2001
  timeout: 600
  enable: on
  connector: serialdev,/dev/ttyTS11,115200n81,LOCAL
  options:
    banner: *banner1
    kickolduser: true

```
