### ISSUE TITLE
error messages on bootup "ser2net[625]: Invalid port name/number: Invalid data to parameter on line 7 column 0"

### ISSUE THREAD

**Issue by MarkSau** [cminyard/ser2net#52]
Hi
if I boot my system i see error messages in syslog
ser2net[625]: Invalid port name/number: Invalid data to parameter on line 30 column 0
and connections to the port are not possible.

after a systemctl restart ser2net the port is accessible.

my ser2net.yaml

```
%YAML 1.1
define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n
connection: &zigbee
  accepter: tcp,20108
  connector: serialdev,/dev/ttyUSB0,115200n81,local
  options:
    kickolduser: true
```

My Proxmox host OS: Linux MSNUC 5.11.22-2-pve #1 SMP PVE 5.11.22-4 (Tue, 20 Jul 2021 21:40:02 +0200) x86_64 GNU/Linux
