### ISSUE TITLE
"Segmentation fault" from "Sending Break"

### ISSUE THREAD

**Issue by mpflaga** [cminyard/ser2net#53]
Hello, I have been very successfully using ser2net on Raspberry Pi 3b+ running Raspbian GNU/Linux 10 (buster), as to provide a connection from Telnet to Serial Ports. Replacing older Cisco Terminal Servers. 
_Thank you. - Big Fan of this work_ 

I have found recently that when I send a "Send Break" I see that Ser2net does a Segment Fault, using Ser2net Version 4.3.3.
I have just built the most recent gensio 8/14/2021 "Initialize sockaddr structures" and still see the problem. And do not see a more recent version of Ser2net. my GIT pulls are up to date on the Master. 

Output
```
tns@thqlccpmsts03:~/ser2net $ sudo /usr/sbin/ser2net -c /etc/ser2net.conf -d -l
Unable to start mdns: Operation not supported
Segmentation fault
tns@thqlccpmsts03:~/ser2net $ 
```
Version
```
tns@thqlccpmsts03:~/ser2net $ sudo /usr/sbin/ser2net -v
/usr/sbin/ser2net version 4.3.3
```

Config File
```
tns@thqlccpmsts03:~/ser2net $ cat /etc/ser2net.conf
%YAML 1.1
---

admin:
  accepter: telnet,1999

define: &banner1 Ser2net \N,\p,\d,\I \r\n

connection: &2002
  accepter: telnet,tcp,2002
  timeout: 600
  enable: on
  connector: serialdev,/dev/ttyTS2,115200n81,LOCAL
  options:
    banner: *banner1
    kickolduser: true

connection: &3002
  accepter: telnet,tcp,3002
  timeout: 600
  enable: on
  connector: serialdev,/dev/ttyTS2,9600n81,LOCAL
  options:
    banner: *banner1
    kickolduser: true
```

FYI - I do not see this segment fault on older version 2.9.1 using RiPi Jessy.

I had expected to see more debug. Where I am not an expert on this, so please let me know if there is more and how to get it. And if there is a way to get the version of gensio that I built, beside saying the lastest. It might be nice for Ser2net's -v command to also print the version of the gensio library it is using. 

Thanks in advance for any help about the Send Break.
