### ISSUE TITLE
Difficulties to set up ser2net / Unable to start mdns: Operation not supported

### ISSUE THREAD

**Issue by nicolas-HORST** [cminyard/ser2net#55]
Hello,

I'm having some difficulties setting up ser2net on my rpi3b+.

Steps ive done:

Update RPI --

```
sudo apt update

sudo apt upgrade

```
--

Download and install gensio 2.2.9 from sourceforge --

```
wget https://sourceforge.net/projects/ser2net/files/gensio-2.2.9.tar.gz

tar -xzvf gensio-2.2.9.tar.gz

cd gensio-2.2.9/

./configure

make

sudo make install
```

--

Download and install libyaml 0.2.5 --

```
wget https://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz

tar -xzvf yaml-0.2.5.tar.gz

cd yaml-0.2.5/

./configure

make

sudo make install
```

--

Download and install ser2net 4.3.3 --

```
wget https://sourceforge.net/projects/ser2net/files/ser2net-4.3.3.tar.gz

tar -xzvf ser2net-4.3.3.tar.gz

cd ser2net-4.3.3/

./configure

make

sudo make install
```

--

After installation I checked with 

`dmesg | grep tty`

where my serial connector is connected to.

-
```
Output:
[54836.730052] usb 1-1.3.1: pl2303 converter now attached to ttyUSB0
[54836.783194] usb 1-1.3.2: pl2303 converter now attached to ttyUSB1
[54836.828199] usb 1-1.3.3: pl2303 converter now attached to ttyUSB2
[54837.039337] usb 1-1.3.4: pl2303 converter now attached to ttyUSB3

```
-

I made sure to go to the usr/local/etc/ser2net folder and create a ser2net.yaml file there

from a previous older version of ser2net (Version: 3.5) I got the contents of the .yaml file and I also tried to make the config like the instructions..

Contents from previous installation:
%YAML 1.1
---
```
define: &confver 1.0
BANNER:banner:this is ser2net TCP port \p device \d  serial parms \s\r\n
4001:telnet:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT banner
```

When starting with any user results in
->
```
pi@raspberrypi:~ $ sudo -u pi ser2net
Unable to start mdns: Operation not supported
yaml parsing error at line 4 column 0: could not find expected ':'

```
Ive also tried putting the ':' where it wanted it but it just gave the same output.

-

Contents of my file as the instructions told me:

```
%YAML 1.1
---
define: &confver 1.0
#
define: &banner Connected to port \N(\d)\r\n
#
default:
      name: local
      value: true
      class: serialdev
#
default:
      name: mdns
      value: false
#
default:
      name: mdns-sysattrs
      value: true
#
connection: &con0
      accepter: telnet(rfc2217),tcp,4001
      connector: serialdev,
                 serial/by-path/platform-3f980000.usb-usb-0:1.1.3.1:1.0-port0,
                 9600n81,local
```

When running with any user results in:
```
pi@raspberrypi:~ $ sudo -u pi ser2net
Unable to start mdns: Operation not supported
```

-

I dont really know what the problem here is as Ive followed the steps that are needed..

**Comment by cminyard** [comment]
On Tue, Oct 05, 2021 at 01:47:00AM -0700, nicolas-HORST wrote:
> Hello,
> 
> I'm having some difficulties setting up ser2net on my rpi3b+.
> 
> Steps ive done:
> 
> Update RPI --
> sudo apt update
> 
> sudo apt upgrade
> --
> 
> Download and install gensio 2.2.9 from sourceforge --
> 
> wget https://sourceforge.net/projects/ser2net/files/gensio-2.2.9.tar.gz
> 
> tar -xzvf gensio-2.2.9.tar.gz
> 
> cd gensio-2.2.9/
> 
> ./configure
> 
> make
> 
> sudo make install
> 
> --
> 
> Download and install libyaml 0.2.5 --
> 
> wget https://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz
> 
> tar -xzvf yaml-0.2.5.tar.gz
> 
> cd yaml-0.2.5/
> 
> ./configure
> 
> make
> 
> sudo make install
> 
> --
> 
> Download and install ser2net 4.3.3 --
> 
> wget https://sourceforge.net/projects/ser2net/files/ser2net-4.3.3.tar.gz
> 
> tar -xzvf ser2net-4.3.3.tar.gz
> 
> cd ser2net-4.3.3/
> 
> ./configure
> 
> make
> 
> sudo make install
> 
> --
> 
> 
> After installation I checked with 
> 
> dmesg | grep tty
> 
> where my serial connector is connected to.
> 
> -
> Output:
> [54836.730052] usb 1-1.3.1: pl2303 converter now attached to ttyUSB0
> [54836.783194] usb 1-1.3.2: pl2303 converter now attached to ttyUSB1
> [54836.828199] usb 1-1.3.3: pl2303 converter now attached to ttyUSB2
> [54837.039337] usb 1-1.3.4: pl2303 converter now attached to ttyUSB3
> 
> -
> 
> I made sure to go to the usr/local/etc/ser2net folder and create a ser2net.yaml file there
> 
> from a previous older version of ser2net (Version: 3.5) I got the contents of the .yaml file and I also tried to make the config like the instructions..
> 
> Contents from previous installation:
> %YAML 1.1
> ---
> define: &confver 1.0
> BANNER:banner:this is ser2net TCP port \p device \d  serial parms \s\r\n
> 4001:telnet:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT banner

This is not yaml, yaml is a different format than the old config
language.  Look at the example yaml config file for help.

You can use the old config format for now in a non-yaml file, (ending in
.conf) but that is deprecated.

-corey

**Comment by nicolas-HORST** [comment]
Hi,

Ive tried it in YAML format:
```

%YAML 1.1
---
define: &confver 1.0
#
define: &banner Connected to port \N(\d)\r\n
#
default:
      name: local
      value: true
      class: serialdev
#
default:
      name: mdns
      value: false
#
default:
      name: mdns-sysattrs
      value: true
#
connection: &con0
      accepter: telnet(rfc2217),tcp,4001
      connector: serialdev,
                 serial/by-path/platform-3f980000.usb-usb-0:1.1.3.1:1.0-port0,
                 9600n81,local

```

Is that not correct or are there missing pieces I need?

Would be using the old .conf format a really bad idea?

**Comment by cminyard** [comment]
On Tue, Oct 05, 2021 at 09:59:00AM -0700, nicolas-HORST wrote:
> Hi,
> 
> Ive tried it in YAML format:
> ```
> 
> %YAML 1.1
> ---
> define: &confver 1.0
> #
> define: &banner Connected to port \N(\d)\r\n
> #
> default:
>       name: local
>       value: true
>       class: serialdev
> #
> default:
>       name: mdns
>       value: false
> #
> default:
>       name: mdns-sysattrs
>       value: true
> #
> connection: &con0
>       accepter: telnet(rfc2217),tcp,4001
>       connector: serialdev,
>                  serial/by-path/platform-3f980000.usb-usb-0:1.1.3.1:1.0-port0,
>                  9600n81,local
> 
> ```
> 
> Is that not correct or are there missing pieces I need?

You need the /dev/ before "serial/" in the path, but beyond that it
looks right to me.  I just tried it out and ser2net was happy with it.
What's going wrong?

> 
> Would be using the old .conf format a really bad idea? 

It's not a huge deal, but you'll have to change some day.  It's a lot
easier to read the YAML version, it's less messy with the by-path stuff,
and it's easier to machine read/generate.  Those were the reasons for
switching.

-corey

**Comment by cminyard** [comment]
On Tue, Oct 05, 2021 at 12:41:03PM -0700, nicolas-HORST wrote:
> I cannot test it right now with the `/dev/` but without it it threw this:
> ```
> ***@***.***:~ $ sudo -u pi ser2net
> Unable to start mdns: Operation not supported

That error is innocuous.  I have fixed it to only print if it matters,
but that's not released yet.  I should probably do a release, there's
enough annoying little bugs like this to merit one.

> ```
> 
> If I would use the .conf file I would only use this part here:
> ```
> BANNER:banner:this is ser2net TCP port \p device \d  serial parms \s\r\n
> 4001:telnet:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT banner
> ```
> going to different telnet ports. 
> But yes you're right. Lets do the YAML way first.
> 
> Maybe I installed something wrong?
> 
> I manually created the `ser2net` directory inside the `/usr/local/`
> I've read that it was before inside the `/usr/sbin/` or some path like that.

I'm not sure what you mean.  If you are compiling it yourself and not
overriding the prefix or directories, if you are doing encrypted
connections there is authentication information in
/usr/local/share/ser2net.  The binary will go into /usr/sbin and the
config files (and host keys if using encryption) in /usr/local/etc/ser2net.

> 
> 
> I will add the `/dev/` before the serial of `serial/by-path/platform-3f980...` and let you know if that changes anything.

Ok, I'm pretty sure that will fix your issue.

-corey

**Comment by nicolas-HORST** [comment]
`I'm not sure what you mean.  If you are compiling it yourself and not
overriding the prefix or directories, if you are doing encrypted
connections there is authentication information in
/usr/local/share/ser2net.  The binary will go into /usr/sbin and the
config files (and host keys if using encryption) in /usr/local/etc/ser2net.`
Sorry for not being clear.
There is no authentication / encryption needed for my use.

`Ok, I'm pretty sure that will fix your issue.`
That would be nice :)

Thanks for the help

-----

Something not related to this issue.

Would it be possible to have it (the install package) - install all the dependencies when installing ser2net? (dependencies as in "Gensio" and "Libyaml")

**Comment by cminyard** [comment]
On Tue, Oct 05, 2021 at 01:21:36PM -0700, nicolas-HORST wrote:
> `I'm not sure what you mean.  If you are compiling it yourself and not
> overriding the prefix or directories, if you are doing encrypted
> connections there is authentication information in
> /usr/local/share/ser2net.  The binary will go into /usr/sbin and the
> config files (and host keys if using encryption) in /usr/local/etc/ser2net.`
> Sorry for not being clear.
> There is no authentication / encryption needed for my use.
> 
> `Ok, I'm pretty sure that will fix your issue.`
> That would be nice :)
> 
> Thanks for the help
> 
> -----
> 
> Something not related to this issue.
> 
> Would it be possible to have it (the install package) - install all the dependencies when installing ser2net? (dependencies as in "Gensio" and "Libyaml")

Not really.  The gensio library has a list and an ubuntu example for
installing the packages you need from the distro for building, because
that's a lot more complicated.  But it will vary from distro to distro
on the naming and commands.  I will add that for ser2net.

In theory, your distro takes care of all this for you.  When you go out
on your own, there's pain to deal with :(.

-corey

**Comment by nicolas-HORST** [comment]
Okay so I've tried the following:
```
%YAML 1.1
---
define: &confver 1.0
#
define: &banner Connected to port \N(\d)\r\n
#
default:
      name: local
      value: true
      class: serialdev
#
default:
      name: mdns
      value: false
#
default:
      name: mdns-sysattrs
      value: true
#
connection: &con0
      accepter: telnet(rfc2217),tcp,4001
      connector: serialdev,
                 /dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3.1:1.0-port0,
                 9600n81,local
```
But it sadly said this again
```
pi@raspberrypi:~ $ sudo -u pi ser2net
Unable to start mdns: Operation not supported
pi@raspberrypi:~ $ sudo -u ser2net ser2net
Unable to start mdns: Operation not supported
pi@raspberrypi:~ $
```

I also tried it with only the connection part of the YAML but that also didn't work

A restart after changing the file also didn't change anything.

Even changing the .YAML to .conf with the old configuration data didn't help and said `operation not supported` again..

------

Could you tell me the correct way to install it and dependencies without having to build it myself?
I probably did something wrong installing it.
I'd delete the card and then start fresh again..
