### ISSUE TITLE
v.4.3.3-1 won't throw any errors when yaml is misconfigured

### ISSUE THREAD

**Issue by williamblair333** [cminyard/ser2net#74]
os,debian bullseye

This is mostly likely ignorance of me not knowing where to look, but I wanted to ask/report.  A misconfigured ser2net.yaml file won't throw any error that I can see.  Specifically, a missing comma after /dev/usb2p2.  I had several other entries just like it, correctly configured.  

```
connection: &con2002
    accepter: tcp,2002
    enable: on
    options:
      banner: *banner-123
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/usb2p2
              115200n81,local
```
