### ISSUE TITLE
Official Docker container image for ser2net? (Dockerfile + docker-compose)

### ISSUE THREAD

**Issue by jippi** [cminyard/ser2net#75]
Hey!

Thanks for an amazing project, I've been using it very successfully with [zigbee2mqtt](https://www.zigbee2mqtt.io)'s support for [remote adapters](https://www.zigbee2mqtt.io/advanced/remote-adapter/connect_to_a_remote_adapter.html#_1-install-ser2net). 

Coming from the `ser2net v2` that was bundled with my OS, v4 is a significant improvement across the board so far.

Since I don't like to fill my host system with a bunch of packages and services, I run `ser2net` within Docker. However, I couldn't find any Docker image of `ser2net` providing more recent version than v2, so I ended up making one.

I'm sharing it here in case you want to provide official Docker builds for the project or in case someone else in the future happen to have the same need as I do on a Pi or similar (I use it on a QNAP NAS).

I would be happy to help doing some of the work required to ship these Docker images automatically as part of your project, and if you don't want to support this as part of the core project, I would be happy to setup an unofficial Docker image for the project.

I have experience doing this kind of work for other Open Source projects like [Pritunl](https://hub.docker.com/r/jippi/pritunl/) and my work as Platform engineer :) 

### Dockerfile

```Dockerfile
FROM debian:bullseye

ARG DEBIAN_FRONTEND=noninteractive
ARG ROOM_ASSISTANT_VERSION=latest
ARG VERSION=4.3.8

RUN set -ex \
    && apt-get update \
    && apt-get install -y libgensio-dev libyaml-dev build-essential wget automake libtool openipmi make pkg-config tini \
    && wget -O /tmp/ser2net.tar.gz https://github.com/cminyard/ser2net/archive/refs/tags/v${VERSION}.tar.gz \
    && tar zxfv /tmp/ser2net.tar.gz -C /tmp \
    && (cd /tmp/ser2net-${VERSION} && ls && ./reconf && ./configure --sysconfdir=/etc && make && make install) \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/ser2net.tar.gz \
        /tmp/ser2net-${VERSION} \
    && apt-get remove -y build-essential wget automake libtool openipmi make pkg-config \
    && apt-get autoremove -y \
    && apt-get clean

ENTRYPOINT ["tini", "--", "ser2net", "-d", "-l", "-c", "/etc/ser2net/ser2net.yaml"]
```

### Docker Compose

```yaml
version: '3.4'
services:
  ser2net:
    image: $your_image_uri_here
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./ser2net.yaml:/etc/ser2net/ser2net.yaml
    devices:
      - /dev/ttyUSB0
```

### ser2net.yaml

```yaml
connection: &con01
  accepter: tcp,20108
  connector: serialdev,/dev/ttyUSB0,115200n81,local
  options:
    kickolduser: true
```

### Building multi-arch image with `buildx`

Using `Makefile`, the build will look like below, which will build a arm64 and amd64 container image automatically

```make
REGISTRY := $YOUR_REGISTRY
PLATFORMS := linux/arm64/v8,linux/amd64
VERSION := 4.3.8 # note, omit the "v" in the tag name
TAG := $(VERSION)

ser2net:
	docker buildx build --pull --push --platform $(PLATFORMS) \
		--tag $(REGISTRY)/iwisystems/docker/ser2net:$(TAG) \
		--build-arg VERSION=$(VERSION) \
		. # Assuming the Dockerfile exist in the same path as you run the command
```
