### ISSUE TITLE
Infinite error message loop "The network write for port <port> had error: Object was not ready for operation"

### ISSUE THREAD

**Issue by SamBissig** [cminyard/ser2net#86]
**Issue description:** 

Our disks get filled up by a log generated by ser2net. We get following lines in the log:

`ser2net[25835]: The network write for port con_ttyShelf_5_0_01 had error: Object was not ready for operation .` 

This message gets printed with a very hight frequency. Our disks gets filled up in a few hours.

**What is the configuration of the failing device?**
```
connection: &con_ttyShelf_5_0_01
  accepter: telnet,tcp,5001
  connector: ratelimit(xmit_delay=5m),serialdev,/dev/ttyShelf_5_0_01,115200n81,local
  options:
    # Set the buffersizes that we could buffer 1s of data
    dev-to-net-bufsize: 115200
    net-to-dev-bufsize: 115200
    max-connections: 2
```

All other devices used use exactly the same configuration. See also [attached configuration](https://github.com/cminyard/ser2net/files/10056665/ser2net.txt)

**What ser2net / gensio version are in use?**
We have seen this issue with older versions. Last time we have seen this was with the latest releases:

Gensio: v2.6.1
Ser2net: v4.3.10

**How often does this happen?**
There is no pattern so far. Once it took 16 days from a one restart to an other, once it took 7 days.

**How can we resolve the issue?**
Restarting ser2net solves the issue. ser2net stops logging to the logs

**What happens before the log filling starts?**
We do not see any special activities or additional errors before ser2net starts printing these error messages.

**Any other information**
- We have between 50 and 56 devices managed by ser2net (number changed over time)
- The incident happens always with the same device. This is a "unique" device that we have only once connected to the server.
- This device is using exactly the same configuration as all the others. It also is not at a special location in the configuration (not at the end or beginning)
- We start ser2net with following parameters `/usr/local/sbin/ser2net -c /etc/ser2net.yaml -P /run/ser2net.pid -t 8 -l`

**Proposed modifications**
- Limit the amount errors printed to the logs
- Try to find a more specific reason for the error. This is a very generic error.
