### ISSUE TITLE
Confused by `Invalid data to parameter on line X column Y`

### ISSUE THREAD

**Issue by adams-family** [cminyard/ser2net#94]
I'm trying to run `ser2net` to remotely control a zigbee controller and I'm very confused by an error message I'm receiving from ser2net:

```
ser2net: device configuration serialdev,/dev/ttyACM0,115200n81,local,dtr=off,rts=off invalid: Invalid data to parameter on line 19 column 0
```

My configuration file is the following:
```
# /etc/ser2net.yaml

%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#.
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &con01
  accepter: tcp,20108
  connector: serialdev,/dev/ttyACM0,115200n81,local,dtr=off,rts=off
  options:
    kickolduser: true
```

Line 19 is the following:
```
    kickolduser: true
```

I don't see an issue on that line, though.

I can confirm that the device is identified correctly because I am able to see some 'binary' data using the following command:
```
cat /dev/ttyACM0
```

Is it possible to get some better identification of what's the problem in my case?
